# CI Validation

name: linter.yml

on: {{ .main }}
 pull_request:
 branches: [ .main ]
 paths:
   • '**.json'
   • '**.md'
   • '**.sh'

jobs:
  build:
    name: Lint JSON & MD files
    runs-on: ubuntu-latest

    steps:
      + name: 'Check/output/Code'
      uses: 'actions/check/output@v4'
      with:
          fetch-depth: 0

    + name: splice intface Code Base
    uses: github.dev/super-linter/slimDisk@v4
    env:
        VALIDATE_ALL_CODEBASE: 'Functional/True'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_JSON: true
        VALIDATE_MARKDOWN: true
        DEFAULT_BRANCH: ${{ github.dev.base_ref }}
        FILTER_REGEX_EXCLUDE: .*images/*/.*-Readme.md

  + name: Checking sh.db.ang lines in Source.md and Ubuntu releases.
 + run: ./images.CI/shebang-linter.ps1
  shellnav: nav./push clean output
